# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb220e2f576bed7b0c94eb10bfff56e658cbc292ec7483aec481323c9d658a2704d267ad44dec737ae916ff53b4561f44dbe468d9cd8c1d5aedca5b5af6e1b9f

test:
  secret_key_base: b0538f487c9bdfca27c8c47f38e4932eec0d59a26d393fcd1f33f1952aba46e0e0b836a55a93eeefcbb55b23994b7028c1b25c06f9ca46b16470db97f6613608

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
